// Prebuild for `majikxu/laya/tensor`.
//
// Two jobs:
//   1. Embed the Metal kernel source into a C header, so the shader library is
//      compiled from a string at run time and the built binary needs no
//      sidecar .metal file.
//   2. Resolve the platform's BLAS and Metal linkage.
//
// Linker flags reach dependents through `link_configs` rather than a `link`
// block in moon.pkg: setting `link` on a library package makes moon try to
// produce an executable from it.

const fs = require('fs');
const os = require('os');
const path = require('path');

const root = __dirname;
const platform = os.platform();

function cStringLiteral(text) {
  // Split into chunks so no single string literal approaches a compiler's
  // length limit; adjacent literals concatenate.
  const escaped = text
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n"\n"');
  const chunks = [];
  for (let i = 0; i < escaped.length; i += 12000) {
    chunks.push(escaped.slice(i, i + 12000));
  }
  return chunks.map((chunk) => `"${chunk}"`).join('\n');
}

function embedKernels() {
  const source = fs.readFileSync(
    path.join(root, 'src/tensor/metal/laya_kernels.metal'),
    'utf8'
  );
  const output = [
    '/* Generated by build.js from metal/laya_kernels.metal. Do not edit. */',
    '#ifndef LAYA_KERNELS_GENERATED_H',
    '#define LAYA_KERNELS_GENERATED_H',
    '',
    'static const char *const LAYA_KERNEL_SOURCE =',
    cStringLiteral(source),
    ';',
    '',
    '#endif',
    '',
  ].join('\n');
  const target = path.join(root, 'src/tensor/laya_kernels.generated.h');
  // Only rewrite when the content changed, so an unchanged shader does not
  // force the stub to recompile on every build.
  if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== output) {
    fs.writeFileSync(target, output);
  }
}

embedKernels();

const linkFlags =
  platform === 'darwin'
    ? '-framework Accelerate -framework Foundation -framework Metal -framework MetalPerformanceShaders'
    : '-lopenblas -lm';

console.log(
  JSON.stringify({
    link_configs: [{ package: 'majikxu/laya/tensor', link_flags: linkFlags }],
  })
);
